title: Franks | Portfolio
description: Showcasing what I build, break, and create. 
show_downloads: true
google_analytics: true
theme: jekyll-theme-hacker
github:
  zip_url: "https://google.com"
  button_text: "Download Google"

